name: Send Daily Betting Guru Email

on:
  schedule:
    # 05:00 UTC = 08:00 Africa/Kampala
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Send email
        env:
          DRY_RUN: "false"
          EMAIL_HOST: "smtp.gmail.com"
          EMAIL_PORT: "587"
          EMAIL_USERNAME: "betguru@gmail.com."
          EMAIL_PASSWORD: "rljtfxauuzvxzegg"
          EMAIL_FROM: "betguru@gmail.com"
          EMAIL_TO: "baptoisaac@gmail.com"
        run: python main.py
